# 1) შექმენით პროგრამა, რომელიც მომხმარებელს შემოატანინებს 2 რიცხვს, ამ ორ რიცხვს შორის გამოიყენეთ ყველა არითმეტიკული და შედარების ოპერატორები
input1 = int(input("Enter First Number: "))
input2 = int(input("Enter Second Number: "))
print(input1 == input2)
print(input1 >= input2)
print(input1 <= input2)
print(input1 != input2)
print(input1 < input2)
print(input1 > input2)
print(input1 + input2)
print(input1 - input2)
print(input1 / input2)
print(input1 // input2)
print(input1 * input2)
print(input1 ** input2)